language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
     - android-23
    - extra-android-m2repository
jdk: oraclejdk7

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew :example:installDebug